# Site settings
title: I am Aziz.
email: azizramos00@gmail.com
description: "Creative Director"
baseurl: ""
url: "http://notansari.com"

# Build settings
markdown: kramdown
permalink: pretty
paginate: 15
sass:
  sass_dir: _sass
