# Site settings
title: i am aziz.
email: azizramos00@gmail.com
description: "Web Developer & Carpenter"
baseurl: ""
url: "http://notansari.com"

# Build settings
markdown: kramdown
permalink: pretty
paginate: 15
sass:
  sass_dir: _sass


exclude:
  - package.json
  - node_modules
  - gulpfiles.js

gems:
- jekyll-compass
